package anthropicauth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode/utf8"
)

const (
	DefaultProviderName = "anthropic"
	DefaultPriority     = 100

	AuthTypeProfile = "profile"
	AuthTypeAPIKey  = "api_key"
	ProviderName    = DefaultProviderName

	credentialDirMode    = 0o700
	credentialFileMode   = 0o600
	credentialFileSuffix = ".json"
	maxCredentialBytes   = 64 << 10
	maxAliasBytes        = 200
	maxProfileBytes      = 256
	maxAPIKeyBytes       = 4096
	maxPriority          = 1_000_000
	maxFilenameBytes     = 160
)

// Credential is the private on-disk representation. APIKey must not be exposed
// through logs, errors, or AccountSummary.
type Credential struct {
	ID        string `json:"id"`
	Alias     string `json:"alias,omitempty"`
	Priority  int    `json:"priority"`
	Disabled  bool   `json:"disabled,omitempty"`
	AuthType  string `json:"auth_type"`
	Profile   string `json:"profile,omitempty"`
	APIKey    string `json:"api_key,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type StoredCredential struct {
	Filename string
	Credential
}

// CreateRequest contains authentication material and user-managed metadata for
// a new account. ID and timestamps are always generated by Store.
type CreateRequest struct {
	AuthType string `json:"auth_type"`
	Profile  string `json:"profile,omitempty"`
	APIKey   string `json:"api_key,omitempty"`
	Alias    string `json:"alias,omitempty"`
	Priority int    `json:"priority,omitempty"`
	Disabled bool   `json:"disabled,omitempty"`
}

// CreateInput is kept as a descriptive alias for Provider/Server callers.
type CreateInput = CreateRequest

type ImportDocument struct {
	Filename string
	Content  []byte
}

type ImportResult struct {
	Imported int      `json:"imported"`
	Skipped  int      `json:"skipped"`
	Files    []string `json:"files,omitempty"`
}

// AccountSummary is safe for API responses. It intentionally has no API key
// field and Source never includes authentication material.
type AccountSummary struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Alias     string `json:"alias,omitempty"`
	Priority  int    `json:"priority"`
	Provider  string `json:"provider"`
	Disabled  bool   `json:"disabled"`
	AuthType  string `json:"auth_type"`
	Profile   string `json:"profile,omitempty"`
	Source    string `json:"source"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type MetadataUpdate struct {
	Alias    *string
	Priority *int
	Disabled *bool
}

type Store struct {
	dir        string
	unsafePath bool
	lock       *sync.RWMutex
}

var credentialStoreLocks sync.Map

func DefaultStoreDir(home string) string {
	home = strings.TrimSpace(home)
	if home == "" {
		return ""
	}
	return filepath.Join(home, "credentials", DefaultProviderName)
}

func NewStore(dir string) *Store {
	dir = strings.TrimSpace(dir)
	unsafePath := false
	if dir != "" {
		if absolute, err := filepath.Abs(dir); err == nil {
			dir = filepath.Clean(absolute)
		}
		if info, err := os.Lstat(dir); err == nil && info.Mode()&os.ModeSymlink != 0 {
			unsafePath = true
		} else if canonical, err := canonicalStorePath(dir); err == nil {
			dir = canonical
		}
	}
	key := filepath.Clean(dir)
	if dir == "" {
		key = ""
	}
	lockValue, _ := credentialStoreLocks.LoadOrStore(key, &sync.RWMutex{})
	return &Store{dir: dir, unsafePath: unsafePath, lock: lockValue.(*sync.RWMutex)}
}

func (s *Store) Dir() string {
	if s == nil {
		return ""
	}
	return s.dir
}

// Load returns every account, including disabled accounts. Results are sorted
// by priority and then opaque ID for deterministic selection and presentation.
func (s *Store) Load() ([]StoredCredential, error) {
	if err := s.validateStore(); err != nil {
		return nil, err
	}
	s.lock.Lock()
	defer s.lock.Unlock()
	return s.loadLocked()
}

// List returns usable candidates only. Disabled accounts are never candidates.
func (s *Store) List() ([]StoredCredential, error) {
	items, err := s.Load()
	if err != nil {
		return nil, err
	}
	candidates := make([]StoredCredential, 0, len(items))
	for _, item := range items {
		if !item.Credential.Disabled {
			candidates = append(candidates, item)
		}
	}
	return candidates, nil
}

func (s *Store) Configured() bool {
	items, err := s.List()
	return err == nil && len(items) > 0
}

func (s *Store) ListAccounts() ([]AccountSummary, error) {
	items, err := s.Load()
	if err != nil {
		return nil, err
	}
	accounts := make([]AccountSummary, 0, len(items))
	for _, item := range items {
		accounts = append(accounts, Summary(item))
	}
	return accounts, nil
}

func Summary(item StoredCredential) AccountSummary {
	credential := item.Credential
	source := "Anthropic API key"
	if credential.AuthType == AuthTypeProfile {
		source = "Anthropic official profile"
	}
	alias := credential.Alias
	if credential.APIKey != "" && strings.Contains(alias, credential.APIKey) {
		alias = ""
	}
	return AccountSummary{
		ID:        credential.ID,
		Name:      source,
		Alias:     alias,
		Priority:  credential.Priority,
		Provider:  DefaultProviderName,
		Disabled:  credential.Disabled,
		AuthType:  credential.AuthType,
		Profile:   credential.Profile,
		Source:    source,
		CreatedAt: credential.CreatedAt,
		UpdatedAt: credential.UpdatedAt,
	}
}

func (s *Store) Create(input any) (StoredCredential, error) {
	request, err := singleCreateRequest(input)
	if err != nil {
		return StoredCredential{}, err
	}
	item, _, err := s.create(request, "")
	return item, err
}

func (s *Store) create(request CreateRequest, requestedFilename string) (StoredCredential, bool, error) {
	if err := s.validateStore(); err != nil {
		return StoredCredential{}, false, err
	}
	credential := normalizeCredential(Credential{
		Alias:    request.Alias,
		Priority: request.Priority,
		Disabled: request.Disabled,
		AuthType: request.AuthType,
		Profile:  request.Profile,
		APIKey:   request.APIKey,
	})
	if credential.Priority == 0 {
		credential.Priority = DefaultPriority
	}
	if err := validateCredential(credential, false); err != nil {
		return StoredCredential{}, false, err
	}
	if requestedFilename != "" {
		if _, err := safeCredentialFilename(requestedFilename); err != nil {
			return StoredCredential{}, false, err
		}
	}

	s.lock.Lock()
	defer s.lock.Unlock()
	if err := s.ensureDirLocked(); err != nil {
		return StoredCredential{}, false, err
	}
	existing, err := s.loadLocked()
	if err != nil {
		return StoredCredential{}, false, err
	}
	identity := credentialIdentity(credential)
	usedFilenames := make(map[string]struct{}, len(existing))
	for _, item := range existing {
		usedFilenames[item.Filename] = struct{}{}
		if credentialIdentity(item.Credential) == identity {
			return item, false, nil
		}
	}

	credential.ID, err = newCredentialID()
	if err != nil {
		return StoredCredential{}, false, errors.New("无法分配 Anthropic 凭据 ID")
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	credential.CreatedAt = now
	credential.UpdatedAt = now
	filename := credential.ID + credentialFileSuffix
	if requestedFilename != "" {
		filename = uniqueCredentialFilename(requestedFilename, credential.ID, usedFilenames)
	}
	if err := s.writeCredentialLocked(filename, credential); err != nil {
		return StoredCredential{}, false, err
	}
	return StoredCredential{Filename: filename, Credential: credential}, true, nil
}

// Import accepts Credential/CreateRequest values or JSON ImportDocument values,
// individually or as slices. This keeps migration and server upload callers from
// needing separate persistence paths.
func (s *Store) Import(input any) (ImportResult, error) {
	requests, filenames, err := importRequests(input)
	if err != nil {
		return ImportResult{}, err
	}
	if len(requests) == 0 {
		return ImportResult{}, errors.New("没有可导入的 Anthropic 凭据")
	}
	result := ImportResult{Files: make([]string, 0, len(requests))}
	for index, request := range requests {
		item, created, err := s.create(request, filenames[index])
		if err != nil {
			return ImportResult{}, fmt.Errorf("第 %d 个 Anthropic 账号保存失败：%w", index+1, err)
		}
		if !created {
			result.Skipped++
			continue
		}
		result.Imported++
		result.Files = append(result.Files, item.Filename)
	}
	return result, nil
}

func (s *Store) GetByID(id string) (StoredCredential, error) {
	id = strings.TrimSpace(id)
	if !validCredentialID(id) {
		return StoredCredential{}, os.ErrNotExist
	}
	items, err := s.Load()
	if err != nil {
		return StoredCredential{}, err
	}
	for _, item := range items {
		if item.Credential.ID == id {
			return item, nil
		}
	}
	return StoredCredential{}, os.ErrNotExist
}

func (s *Store) UpdateMetadata(id string, update MetadataUpdate) (StoredCredential, error) {
	if err := s.validateStore(); err != nil {
		return StoredCredential{}, err
	}
	id = strings.TrimSpace(id)
	if !validCredentialID(id) {
		return StoredCredential{}, os.ErrNotExist
	}
	s.lock.Lock()
	defer s.lock.Unlock()
	items, err := s.loadLocked()
	if err != nil {
		return StoredCredential{}, err
	}
	for _, item := range items {
		if item.Credential.ID != id {
			continue
		}
		if update.Alias != nil {
			item.Credential.Alias = strings.TrimSpace(*update.Alias)
		}
		if update.Priority != nil {
			item.Credential.Priority = *update.Priority
		}
		if update.Disabled != nil {
			item.Credential.Disabled = *update.Disabled
		}
		item.Credential.UpdatedAt = time.Now().UTC().Format(time.RFC3339Nano)
		if err := validateCredential(item.Credential, true); err != nil {
			return StoredCredential{}, err
		}
		if err := s.writeCredentialLocked(item.Filename, item.Credential); err != nil {
			return StoredCredential{}, err
		}
		return item, nil
	}
	return StoredCredential{}, os.ErrNotExist
}

func (s *Store) Delete(id string) error {
	if err := s.validateStore(); err != nil {
		return err
	}
	id = strings.TrimSpace(id)
	if !validCredentialID(id) {
		return os.ErrNotExist
	}
	s.lock.Lock()
	defer s.lock.Unlock()
	items, err := s.loadLocked()
	if err != nil {
		return err
	}
	for _, item := range items {
		if item.Credential.ID != id {
			continue
		}
		filename, err := safeCredentialFilename(item.Filename)
		if err != nil {
			return err
		}
		path := filepath.Join(s.dir, filename)
		info, err := os.Lstat(path)
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("Anthropic 凭据目标路径不安全")
		}
		if err := os.Remove(path); err != nil {
			return errors.New("删除 Anthropic 凭据失败")
		}
		return syncDirectory(s.dir)
	}
	return os.ErrNotExist
}

func (s *Store) validateStore() error {
	if s == nil || strings.TrimSpace(s.dir) == "" {
		return errors.New("Anthropic 本地凭据库路径未配置")
	}
	if s.unsafePath {
		return errors.New("Anthropic 本地凭据库路径不安全")
	}
	return nil
}

func (s *Store) loadLocked() ([]StoredCredential, error) {
	if err := rejectSymlinkPathComponents(s.dir); err != nil {
		return nil, err
	}
	info, statErr := os.Lstat(s.dir)
	if errors.Is(statErr, os.ErrNotExist) {
		return []StoredCredential{}, nil
	}
	if statErr != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("Anthropic 本地凭据库路径不安全")
	}
	if err := os.Chmod(s.dir, credentialDirMode); err != nil {
		return nil, errors.New("设置 Anthropic 本地凭据库权限失败")
	}
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		return nil, errors.New("读取 Anthropic 本地凭据库失败")
	}
	items := make([]StoredCredential, 0, len(entries))
	usedIDs := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(strings.ToLower(entry.Name()), credentialFileSuffix) {
			continue
		}
		if entry.Type()&os.ModeSymlink != 0 {
			continue
		}
		filename, err := safeCredentialFilename(entry.Name())
		if err != nil {
			continue
		}
		path := filepath.Join(s.dir, filename)
		fileInfo, err := os.Lstat(path)
		if err != nil || !fileInfo.Mode().IsRegular() || fileInfo.Mode()&os.ModeSymlink != 0 {
			continue
		}
		file, err := os.Open(path)
		if err != nil {
			return nil, errors.New("读取 Anthropic 凭据失败")
		}
		data, readErr := io.ReadAll(io.LimitReader(file, maxCredentialBytes+1))
		closeErr := file.Close()
		if readErr != nil || closeErr != nil || len(data) > maxCredentialBytes {
			return nil, errors.New("读取 Anthropic 凭据失败")
		}
		credential, err := decodeCredential(data)
		if err != nil {
			return nil, errors.New("Anthropic 凭据已损坏")
		}
		migrated := false
		if !validCredentialID(credential.ID) {
			credential.ID, err = newCredentialID()
			if err != nil {
				return nil, errors.New("无法迁移 Anthropic 凭据 ID")
			}
			migrated = true
		}
		if _, duplicate := usedIDs[credential.ID]; duplicate {
			credential.ID, err = newCredentialID()
			if err != nil {
				return nil, errors.New("无法迁移重复的 Anthropic 凭据 ID")
			}
			migrated = true
		}
		usedIDs[credential.ID] = struct{}{}
		if credential.Priority == 0 {
			credential.Priority = DefaultPriority
			migrated = true
		}
		now := time.Now().UTC().Format(time.RFC3339Nano)
		if credential.CreatedAt == "" {
			credential.CreatedAt = now
			migrated = true
		}
		if credential.UpdatedAt == "" {
			credential.UpdatedAt = credential.CreatedAt
			migrated = true
		}
		if err := validateCredential(credential, true); err != nil {
			return nil, errors.New("Anthropic 凭据已损坏")
		}
		if migrated {
			if err := s.writeCredentialLocked(filename, credential); err != nil {
				return nil, errors.New("迁移 Anthropic 凭据失败")
			}
		} else if err := os.Chmod(path, credentialFileMode); err != nil {
			return nil, errors.New("设置 Anthropic 凭据权限失败")
		}
		items = append(items, StoredCredential{Filename: filename, Credential: credential})
	}
	sortCredentials(items)
	return items, nil
}

func (s *Store) ensureDirLocked() error {
	if err := rejectSymlinkPathComponents(s.dir); err != nil {
		return err
	}
	parent := filepath.Dir(s.dir)
	if parent != "." && parent != s.dir {
		if err := os.MkdirAll(parent, credentialDirMode); err != nil {
			return errors.New("创建 Anthropic 本地凭据库失败")
		}
		if err := rejectSymlinkPathComponents(parent); err != nil {
			return err
		}
	}
	if info, err := os.Lstat(s.dir); err == nil {
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("Anthropic 本地凭据库路径不安全")
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return errors.New("检查 Anthropic 本地凭据库失败")
	} else if err := os.Mkdir(s.dir, credentialDirMode); err != nil && !errors.Is(err, os.ErrExist) {
		return errors.New("创建 Anthropic 本地凭据库失败")
	}
	if err := os.Chmod(s.dir, credentialDirMode); err != nil {
		return errors.New("设置 Anthropic 本地凭据库权限失败")
	}
	return nil
}

func (s *Store) writeCredentialLocked(filename string, credential Credential) error {
	filename, err := safeCredentialFilename(filename)
	if err != nil {
		return err
	}
	credential = normalizeCredential(credential)
	if err := validateCredential(credential, true); err != nil {
		return err
	}
	data, err := json.MarshalIndent(credential, "", "  ")
	if err != nil || len(data)+1 > maxCredentialBytes {
		return errors.New("序列化 Anthropic 凭据失败")
	}
	data = append(data, '\n')
	temp, err := os.CreateTemp(s.dir, ".anthropic-credential-*")
	if err != nil {
		return errors.New("创建 Anthropic 凭据临时文件失败")
	}
	tempName := temp.Name()
	complete := false
	defer func() {
		_ = temp.Close()
		if !complete {
			_ = os.Remove(tempName)
		}
	}()
	if err := temp.Chmod(credentialFileMode); err != nil {
		return errors.New("设置 Anthropic 凭据权限失败")
	}
	if _, err := temp.Write(data); err != nil {
		return errors.New("写入 Anthropic 凭据失败")
	}
	if err := temp.Sync(); err != nil {
		return errors.New("同步 Anthropic 凭据失败")
	}
	if err := temp.Close(); err != nil {
		return errors.New("关闭 Anthropic 凭据文件失败")
	}
	target := filepath.Join(s.dir, filename)
	if info, err := os.Lstat(target); err == nil && (!info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0) {
		return errors.New("Anthropic 凭据目标路径不安全")
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return errors.New("检查 Anthropic 凭据目标失败")
	}
	if err := os.Rename(tempName, target); err != nil {
		return errors.New("保存 Anthropic 凭据失败")
	}
	if err := os.Chmod(target, credentialFileMode); err != nil {
		return errors.New("设置 Anthropic 凭据权限失败")
	}
	complete = true
	return syncDirectory(s.dir)
}

func decodeCredential(data []byte) (Credential, error) {
	if len(data) == 0 || len(data) > maxCredentialBytes {
		return Credential{}, errors.New("invalid credential")
	}
	var credential Credential
	decoder := json.NewDecoder(strings.NewReader(string(data)))
	if err := decoder.Decode(&credential); err != nil {
		return Credential{}, errors.New("invalid credential")
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return Credential{}, errors.New("invalid credential")
	}
	credential = normalizeCredential(credential)
	if err := validateCredential(credential, false); err != nil {
		return Credential{}, errors.New("invalid credential")
	}
	return credential, nil
}

func normalizeCredential(credential Credential) Credential {
	credential.ID = strings.TrimSpace(credential.ID)
	credential.Alias = strings.TrimSpace(credential.Alias)
	credential.AuthType = strings.ToLower(strings.TrimSpace(credential.AuthType))
	credential.Profile = strings.TrimSpace(credential.Profile)
	credential.APIKey = strings.TrimSpace(credential.APIKey)
	credential.CreatedAt = strings.TrimSpace(credential.CreatedAt)
	credential.UpdatedAt = strings.TrimSpace(credential.UpdatedAt)
	return credential
}

func validateCredential(credential Credential, persisted bool) error {
	if !utf8.ValidString(credential.Alias) || len(credential.Alias) > maxAliasBytes {
		return fmt.Errorf("Anthropic 账号别名不能超过 %d 字节", maxAliasBytes)
	}
	if credential.Priority < 0 || credential.Priority > maxPriority || (persisted && credential.Priority == 0) {
		return fmt.Errorf("Anthropic 账号优先级必须在 1 到 %d 之间", maxPriority)
	}
	if len(credential.Profile) > maxProfileBytes || !utf8.ValidString(credential.Profile) {
		return fmt.Errorf("Anthropic profile 名不能超过 %d 字节", maxProfileBytes)
	}
	if len(credential.APIKey) > maxAPIKeyBytes || !utf8.ValidString(credential.APIKey) {
		return fmt.Errorf("Anthropic API key 不能超过 %d 字节", maxAPIKeyBytes)
	}
	for _, field := range []string{credential.ID, credential.Alias, credential.AuthType, credential.Profile, credential.APIKey, credential.CreatedAt, credential.UpdatedAt} {
		if strings.ContainsRune(field, 0) {
			return errors.New("Anthropic 凭据包含无效字符")
		}
	}
	switch credential.AuthType {
	case AuthTypeProfile:
		if credential.Profile == "" || credential.APIKey != "" {
			return errors.New("Anthropic profile 凭据必须只包含 profile 名")
		}
		if containsControl(credential.Profile) {
			return errors.New("Anthropic profile 名包含无效字符")
		}
	case AuthTypeAPIKey:
		if credential.APIKey == "" || credential.Profile != "" {
			return errors.New("Anthropic API key 凭据必须只包含 API key")
		}
		if containsControl(credential.APIKey) {
			return errors.New("Anthropic API key 包含无效字符")
		}
	default:
		return errors.New("Anthropic 凭据 auth_type 无效")
	}
	if persisted {
		if !validCredentialID(credential.ID) {
			return errors.New("Anthropic 凭据缺少稳定 ID")
		}
		if !validTimestamp(credential.CreatedAt) || !validTimestamp(credential.UpdatedAt) {
			return errors.New("Anthropic 凭据时间戳无效")
		}
	}
	return nil
}

func containsControl(value string) bool {
	for _, r := range value {
		if r < 0x20 || r == 0x7f {
			return true
		}
	}
	return false
}

func validTimestamp(value string) bool {
	if value == "" || len(value) > 64 {
		return false
	}
	_, err := time.Parse(time.RFC3339Nano, value)
	return err == nil
}

func newCredentialID() (string, error) {
	var random [18]byte
	if _, err := rand.Read(random[:]); err != nil {
		return "", err
	}
	return "anthropic_" + base64.RawURLEncoding.EncodeToString(random[:]), nil
}

func validCredentialID(value string) bool {
	if !strings.HasPrefix(value, "anthropic_") || len(value) < 24 || len(value) > 64 {
		return false
	}
	decoded, err := base64.RawURLEncoding.DecodeString(strings.TrimPrefix(value, "anthropic_"))
	return err == nil && len(decoded) >= 16
}

func credentialIdentity(credential Credential) string {
	var value string
	if credential.AuthType == AuthTypeProfile {
		value = credential.Profile
	} else {
		value = credential.APIKey
	}
	hash := sha256.Sum256([]byte(credential.AuthType + "\x00" + value))
	return credential.AuthType + ":" + hex.EncodeToString(hash[:])
}

func sortCredentials(items []StoredCredential) {
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].Credential.Priority != items[j].Credential.Priority {
			return items[i].Credential.Priority < items[j].Credential.Priority
		}
		return items[i].Credential.ID < items[j].Credential.ID
	})
}

func singleCreateRequest(input any) (CreateRequest, error) {
	switch value := input.(type) {
	case CreateRequest:
		return value, nil
	case *CreateRequest:
		if value != nil {
			return *value, nil
		}
	case Credential:
		return requestFromCredential(value), nil
	case *Credential:
		if value != nil {
			return requestFromCredential(*value), nil
		}
	}
	return CreateRequest{}, errors.New("Anthropic 凭据内容无效")
}

func importRequests(input any) ([]CreateRequest, []string, error) {
	switch value := input.(type) {
	case CreateRequest:
		return []CreateRequest{value}, []string{""}, nil
	case *CreateRequest:
		if value == nil {
			return nil, nil, errors.New("Anthropic 凭据内容无效")
		}
		return []CreateRequest{*value}, []string{""}, nil
	case []CreateRequest:
		return value, make([]string, len(value)), nil
	case Credential:
		return []CreateRequest{requestFromCredential(value)}, []string{""}, nil
	case *Credential:
		if value == nil {
			return nil, nil, errors.New("Anthropic 凭据内容无效")
		}
		return []CreateRequest{requestFromCredential(*value)}, []string{""}, nil
	case []Credential:
		requests := make([]CreateRequest, len(value))
		for i := range value {
			requests[i] = requestFromCredential(value[i])
		}
		return requests, make([]string, len(value)), nil
	case ImportDocument:
		request, err := decodeImportDocument(value)
		return []CreateRequest{request}, []string{value.Filename}, err
	case []ImportDocument:
		requests := make([]CreateRequest, len(value))
		filenames := make([]string, len(value))
		for i := range value {
			request, err := decodeImportDocument(value[i])
			if err != nil {
				return nil, nil, fmt.Errorf("第 %d 个 Anthropic 凭据内容无效", i+1)
			}
			requests[i] = request
			filenames[i] = value[i].Filename
		}
		return requests, filenames, nil
	default:
		return nil, nil, errors.New("Anthropic 凭据内容无效")
	}
}

func requestFromCredential(credential Credential) CreateRequest {
	return CreateRequest{
		AuthType: credential.AuthType,
		Profile:  credential.Profile,
		APIKey:   credential.APIKey,
		Alias:    credential.Alias,
		Priority: credential.Priority,
		Disabled: credential.Disabled,
	}
}

func decodeImportDocument(document ImportDocument) (CreateRequest, error) {
	if len(document.Content) == 0 || len(document.Content) > maxCredentialBytes {
		return CreateRequest{}, errors.New("Anthropic 凭据内容无效")
	}
	var request CreateRequest
	decoder := json.NewDecoder(strings.NewReader(string(document.Content)))
	if err := decoder.Decode(&request); err != nil {
		return CreateRequest{}, errors.New("Anthropic 凭据内容无效")
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return CreateRequest{}, errors.New("Anthropic 凭据内容无效")
	}
	return request, nil
}

func uniqueCredentialFilename(requested, id string, used map[string]struct{}) string {
	filename, _ := safeCredentialFilename(requested)
	if _, exists := used[filename]; !exists {
		return filename
	}
	stem := strings.TrimSuffix(filename, filepath.Ext(filename))
	suffix := strings.TrimPrefix(id, "anthropic_")
	if len(suffix) > 8 {
		suffix = suffix[:8]
	}
	candidate := stem + "-" + suffix + credentialFileSuffix
	if _, exists := used[candidate]; !exists {
		return candidate
	}
	for index := 2; ; index++ {
		candidate = fmt.Sprintf("%s-%s-%d%s", stem, suffix, index, credentialFileSuffix)
		if _, exists := used[candidate]; !exists {
			return candidate
		}
	}
}

func safeCredentialFilename(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" || value == "." || value == string(filepath.Separator) || value != filepath.Base(value) || strings.ContainsAny(value, "\x00/\\") {
		return "", errors.New("Anthropic 凭据文件名无效")
	}
	if !strings.HasSuffix(strings.ToLower(value), credentialFileSuffix) {
		value += credentialFileSuffix
	}
	if len(value) > maxFilenameBytes {
		return "", errors.New("Anthropic 凭据文件名无效")
	}
	return value, nil
}

func canonicalStorePath(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	current := absolute
	missing := make([]string, 0, 4)
	for {
		if _, err := os.Lstat(current); err == nil {
			resolved, err := filepath.EvalSymlinks(current)
			if err != nil {
				return "", err
			}
			for index := len(missing) - 1; index >= 0; index-- {
				resolved = filepath.Join(resolved, missing[index])
			}
			return filepath.Clean(resolved), nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", errors.New("no existing credential path ancestor")
		}
		missing = append(missing, filepath.Base(current))
		current = parent
	}
}

func rejectSymlinkPathComponents(path string) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return errors.New("Anthropic 本地凭据库路径无效")
	}
	volume := filepath.VolumeName(absolute)
	remainder := strings.TrimPrefix(absolute, volume)
	current := volume + string(filepath.Separator)
	for _, component := range strings.Split(strings.Trim(remainder, string(filepath.Separator)), string(filepath.Separator)) {
		if component == "" {
			continue
		}
		current = filepath.Join(current, component)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return errors.New("检查 Anthropic 本地凭据库路径失败")
		}
		if info.Mode()&os.ModeSymlink != 0 || (current != absolute && !info.IsDir()) {
			return errors.New("Anthropic 本地凭据库路径不安全")
		}
	}
	return nil
}

func syncDirectory(dir string) error {
	file, err := os.Open(dir)
	if err != nil {
		return errors.New("同步 Anthropic 本地凭据库失败")
	}
	defer file.Close()
	if err := file.Sync(); err != nil {
		return errors.New("同步 Anthropic 本地凭据库失败")
	}
	return nil
}
