package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
)

// OAuthAppUserProvision describes a JIT OIDC identity binding. PasswordHash is
// an unusable random local credential generated by the server; it exists only
// to keep password-login timing and storage invariants consistent.
type OAuthAppUserProvision struct {
	Issuer       string
	Subject      string
	Handle       string
	PasswordHash string
	Email        string
	DisplayName  string
}

// FindOrCreateOAuthAppUser resolves an existing issuer+subject binding or
// atomically creates the local user and identity when provisioning is open.
// The first local user is also eligible inside this transaction even when
// allowCreate is false, preventing concurrent closed-registration callbacks
// from both observing an empty user table. Email is mutable metadata and is
// never used to select or link an account.
func (s *Store) FindOrCreateOAuthAppUser(ctx context.Context, provision OAuthAppUserProvision, allowCreate bool) (User, bool, error) {
	identity, err := canonicalOAuthAppIdentity(OAuthAppIdentity{
		Issuer:      provision.Issuer,
		Subject:     provision.Subject,
		UserID:      "placeholder",
		Email:       provision.Email,
		DisplayName: provision.DisplayName,
	})
	if err != nil {
		return User{}, false, err
	}
	provision.Handle = strings.TrimSpace(provision.Handle)
	provision.PasswordHash = strings.TrimSpace(provision.PasswordHash)

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return User{}, false, err
	}
	defer tx.Rollback()

	if user, found, err := oauthAppUserByIdentityTx(ctx, tx, identity.Issuer, identity.Subject); err != nil {
		return User{}, false, err
	} else if found {
		if _, err := tx.ExecContext(ctx, `UPDATE oauth_app_identities SET email = NULLIF(?, ''), display_name = NULLIF(?, ''), updated_at = ? WHERE issuer = ? AND subject = ?`, identity.Email, identity.DisplayName, Now(), identity.Issuer, identity.Subject); err != nil {
			return User{}, false, err
		}
		if err := tx.Commit(); err != nil {
			return User{}, false, err
		}
		return user, false, nil
	}
	var existingUsers int
	if err := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM users`).Scan(&existingUsers); err != nil {
		return User{}, false, err
	}
	if !allowCreate && existingUsers != 0 {
		return User{}, false, sql.ErrNoRows
	}
	if provision.PasswordHash == "" {
		return User{}, false, errors.New("password hash is required for OAuth app user provisioning")
	}
	handle, handleKey, err := CanonicalHandle(provision.Handle)
	if err != nil {
		return User{}, false, err
	}
	now := Now()
	user := User{ID: NewID(), Username: handle, Handle: handle, Role: "user", CreatedAt: now}
	if _, err := tx.ExecContext(ctx, `INSERT INTO users (id, username, handle, handle_key, password_hash, role, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`, user.ID, user.Username, user.Handle, handleKey, provision.PasswordHash, user.Role, user.CreatedAt); err != nil {
		if isUniqueConstraint(err) {
			return User{}, false, fmt.Errorf("%w: OAuth app user handle already exists", ErrConflict)
		}
		return User{}, false, err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO oauth_app_identities (issuer, subject, user_id, email, display_name, created_at, updated_at) VALUES (?, ?, ?, NULLIF(?, ''), NULLIF(?, ''), ?, ?)`, identity.Issuer, identity.Subject, user.ID, identity.Email, identity.DisplayName, now, now); err != nil {
		if isUniqueConstraint(err) {
			return User{}, false, fmt.Errorf("%w: OAuth app identity was created concurrently", ErrConflict)
		}
		return User{}, false, err
	}
	if existingUsers == 0 {
		if err := assignUnownedProjectsTx(ctx, tx, user.ID, now); err != nil {
			return User{}, false, err
		}
	}
	if err := tx.Commit(); err != nil {
		return User{}, false, err
	}
	return user, true, nil
}

func (s *Store) GetUser(ctx context.Context, userID string) (User, error) {
	userID = strings.TrimSpace(userID)
	if userID == "" {
		return User{}, errors.New("user id is required")
	}
	var user User
	err := s.db.QueryRowContext(ctx, `SELECT id, username, handle, role, created_at FROM users WHERE id = ?`, userID).Scan(&user.ID, &user.Username, &user.Handle, &user.Role, &user.CreatedAt)
	return user, err
}

func oauthAppUserByIdentityTx(ctx context.Context, tx *sql.Tx, issuer, subject string) (User, bool, error) {
	var user User
	err := tx.QueryRowContext(ctx, `SELECT u.id, u.username, u.handle, u.role, u.created_at FROM oauth_app_identities i JOIN users u ON u.id = i.user_id WHERE i.issuer = ? AND i.subject = ?`, issuer, subject).Scan(&user.ID, &user.Username, &user.Handle, &user.Role, &user.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, false, nil
	}
	return user, err == nil, err
}
